sudo: false

language: python
os:
  - linux

python:
 - "2.6"
 - "2.7"

ActiveRecord::Base.establish_connection :adapter => 'sqlite3',
                                        :database => ':memory:'

install: "pip install -r requirements.txt"

script: pytest
